version: '3.8'
services:
  db:
    image: mysql:8
    container_name: taskdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - tasknet

  app:
    build: .
    container_name: taskapp
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: taskdb
      DB_USER: user
      DB_PASS: password
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - tasknet

networks:
  tasknet:
    driver: bridge